name: Cron
on:
  schedule:
    - cron: '0 20 * * *'
  deployment_status:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsSL -X POST '${{ vars.BOT_BASE_URL }}${{ secrets.BOT_CRON_ACTION }}'
